name: node.jsci 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          module.exports = {
SESSION_ID: process.env.SESSION_ID || "ANJU-MD=6dNDDSpC#3-dBq0id2NFrdAqPhkl1J-L8iT-lP53051fRikdtYFU",

          WHATSAPP_PHONE_NUMBER: ${{ secrets. +27781673022 }}

      - name: Build and start WhatsApp bot
        run: |
          npm run build
          npm run start

      - name: Keep WhatsApp bot running
        run: |
          while true
          do
            sleep 1
          done
```
